repos:
  - repo: https://github.com/google/yapf
    rev: v0.40.0
    hooks:
      - id: yapf
        args: ["--in-place", "--verbose"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        args: ["--number", "--table-width", "200", '--disable-escape', 'backslash', '--disable-escape', 'link-enclosure']
        additional_dependencies:
          - "mdformat-openmmlab>=0.0.4"
          - mdformat_frontmatter
          - linkify-it-py
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args: ["--write-changes", "-L", "te, Ue, nd, hist", "--skip", "*.ipynb"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-filepath
          - LICENSE        # defaults to: LICENSE.txt
          - --use-current-year
          - --no-extra-eol                # see below
  - repo: https://github.com/myint/docformatter
    rev: v1.7.3
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "79"]
